### ISSUE TITLE
if meilisearch has a full disk, all write requests fail

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-lib#77]
This also leads to non-functional api calls e.g. in metal-api

**Comment by vknabel** [comment]
Currently this is expected behavior, as we wanted to avoid performing changes that are not reflected in meilisearch (e.g. changes to machine / ip ownership).

If we want to keep the original constraint, we'd need to implement the S3 backup sidecar for meilisearch. In that case we could reduce the value passed to `--auditing-index-keep` from 10 to let's say 2 or three. Then the meilisearch auditing adapter will automatically clean up excessive indices.

Would this solve this issue in production?

**Comment by majst01** [comment]
is `--auditing-index-keep=10` defaulted if not given ?

**Comment by vknabel** [comment]
Yes, the default if not given is `--auditing-index-keep=10` and `--auditing-index-interval=@daily`, resulting in 10 days of data.

**Comment by vknabel** [comment]
As we recently introduced the S3 backup sidecar for meilisearch, we could further reduce `--auditing-index-keep` to just a few days to further reduce the volume size, if an optimization is still needed.
Otherwise I'd suggest to close this issue.

**Comment by Gerrit91** [comment]
As we introduced the index rotation, I think this can be closed.
